package system

// Code Action
// LOG_INFO
const (
	SYSLOG_LOG_EMERG   = "LOG_EMERG"
	SYSLOG_LOG_ALERT   = "LOG_ALERT"
	SYSLOG_LOG_CRIT    = "LOG_CRIT"
	SYSLOG_LOG_ERR     = "LOG_ERR"
	SYSLOG_LOG_WARNING = "LOG_WARNING"
	SYSLOG_LOG_NOTICE  = "LOG_NOTICE"
	SYSLOG_LOG_INFO    = "LOG_INFO"
	SYSLOG_LOG_DEBUG   = "LOG_DEBUG"
)
