# qryn bun builder
FROM oven/bun:slim

# BUILD FORCE
ENV BUILD 20231027
ENV PORT 3100

COPY . /app
WORKDIR /app
RUN rm -rf package-lock.json
RUN bun install

# Expose Ports
EXPOSE 3100
CMD [ "bun", "--bun", "qryn.mjs" ]
