# qryn bun builder
FROM oven/bun:latest

COPY . /app
WORKDIR /app

RUN groupadd -r qryn && useradd -r -g qryn -m qryn && chown -R qryn:qryn /app
USER qryn

RUN rm -rf package-lock.json
RUN bun install

# Expose Ports
EXPOSE 3100
CMD [ "bun", "--bun", "qryn.mjs" ]
