// source: google/v1/profile.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.google.v1.Function', null, global);
goog.exportSymbol('proto.google.v1.Label', null, global);
goog.exportSymbol('proto.google.v1.Line', null, global);
goog.exportSymbol('proto.google.v1.Location', null, global);
goog.exportSymbol('proto.google.v1.Mapping', null, global);
goog.exportSymbol('proto.google.v1.Profile', null, global);
goog.exportSymbol('proto.google.v1.Sample', null, global);
goog.exportSymbol('proto.google.v1.ValueType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Profile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.v1.Profile.repeatedFields_, null);
};
goog.inherits(proto.google.v1.Profile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Profile.displayName = 'proto.google.v1.Profile';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.ValueType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.v1.ValueType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.ValueType.displayName = 'proto.google.v1.ValueType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Sample = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.v1.Sample.repeatedFields_, null);
};
goog.inherits(proto.google.v1.Sample, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Sample.displayName = 'proto.google.v1.Sample';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Label = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.v1.Label, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Label.displayName = 'proto.google.v1.Label';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Mapping = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.v1.Mapping, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Mapping.displayName = 'proto.google.v1.Mapping';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Location = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.v1.Location.repeatedFields_, null);
};
goog.inherits(proto.google.v1.Location, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Location.displayName = 'proto.google.v1.Location';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Line = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.v1.Line, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Line.displayName = 'proto.google.v1.Line';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.v1.Function = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.v1.Function, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.v1.Function.displayName = 'proto.google.v1.Function';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.v1.Profile.repeatedFields_ = [1,2,3,4,5,6,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Profile.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Profile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Profile} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Profile.toObject = function(includeInstance, msg) {
  var f, obj = {
    sampleTypeList: jspb.Message.toObjectList(msg.getSampleTypeList(),
    proto.google.v1.ValueType.toObject, includeInstance),
    sampleList: jspb.Message.toObjectList(msg.getSampleList(),
    proto.google.v1.Sample.toObject, includeInstance),
    mappingList: jspb.Message.toObjectList(msg.getMappingList(),
    proto.google.v1.Mapping.toObject, includeInstance),
    locationList: jspb.Message.toObjectList(msg.getLocationList(),
    proto.google.v1.Location.toObject, includeInstance),
    functionList: jspb.Message.toObjectList(msg.getFunctionList(),
    proto.google.v1.Function.toObject, includeInstance),
    stringTableList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    dropFrames: jspb.Message.getFieldWithDefault(msg, 7, 0),
    keepFrames: jspb.Message.getFieldWithDefault(msg, 8, 0),
    timeNanos: jspb.Message.getFieldWithDefault(msg, 9, 0),
    durationNanos: jspb.Message.getFieldWithDefault(msg, 10, 0),
    periodType: (f = msg.getPeriodType()) && proto.google.v1.ValueType.toObject(includeInstance, f),
    period: jspb.Message.getFieldWithDefault(msg, 12, 0),
    commentList: (f = jspb.Message.getRepeatedField(msg, 13)) == null ? undefined : f,
    defaultSampleType: jspb.Message.getFieldWithDefault(msg, 14, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Profile}
 */
proto.google.v1.Profile.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Profile;
  return proto.google.v1.Profile.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Profile} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Profile}
 */
proto.google.v1.Profile.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.v1.ValueType;
      reader.readMessage(value,proto.google.v1.ValueType.deserializeBinaryFromReader);
      msg.addSampleType(value);
      break;
    case 2:
      var value = new proto.google.v1.Sample;
      reader.readMessage(value,proto.google.v1.Sample.deserializeBinaryFromReader);
      msg.addSample(value);
      break;
    case 3:
      var value = new proto.google.v1.Mapping;
      reader.readMessage(value,proto.google.v1.Mapping.deserializeBinaryFromReader);
      msg.addMapping(value);
      break;
    case 4:
      var value = new proto.google.v1.Location;
      reader.readMessage(value,proto.google.v1.Location.deserializeBinaryFromReader);
      msg.addLocation(value);
      break;
    case 5:
      var value = new proto.google.v1.Function;
      reader.readMessage(value,proto.google.v1.Function.deserializeBinaryFromReader);
      msg.addFunction(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addStringTable(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDropFrames(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKeepFrames(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeNanos(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDurationNanos(value);
      break;
    case 11:
      var value = new proto.google.v1.ValueType;
      reader.readMessage(value,proto.google.v1.ValueType.deserializeBinaryFromReader);
      msg.setPeriodType(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setPeriod(value);
      break;
    case 13:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addComment(values[i]);
      }
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDefaultSampleType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Profile.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Profile.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Profile} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Profile.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSampleTypeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.v1.ValueType.serializeBinaryToWriter
    );
  }
  f = message.getSampleList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.v1.Sample.serializeBinaryToWriter
    );
  }
  f = message.getMappingList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.v1.Mapping.serializeBinaryToWriter
    );
  }
  f = message.getLocationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.v1.Location.serializeBinaryToWriter
    );
  }
  f = message.getFunctionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.google.v1.Function.serializeBinaryToWriter
    );
  }
  f = message.getStringTableList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getDropFrames();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getKeepFrames();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getTimeNanos();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
  f = message.getDurationNanos();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getPeriodType();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.google.v1.ValueType.serializeBinaryToWriter
    );
  }
  f = message.getPeriod();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getCommentList();
  if (f.length > 0) {
    writer.writePackedInt64(
      13,
      f
    );
  }
  f = message.getDefaultSampleType();
  if (f !== 0) {
    writer.writeInt64(
      14,
      f
    );
  }
};


/**
 * repeated ValueType sample_type = 1;
 * @return {!Array<!proto.google.v1.ValueType>}
 */
proto.google.v1.Profile.prototype.getSampleTypeList = function() {
  return /** @type{!Array<!proto.google.v1.ValueType>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.ValueType, 1));
};


/**
 * @param {!Array<!proto.google.v1.ValueType>} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setSampleTypeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.v1.ValueType=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.ValueType}
 */
proto.google.v1.Profile.prototype.addSampleType = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.v1.ValueType, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearSampleTypeList = function() {
  return this.setSampleTypeList([]);
};


/**
 * repeated Sample sample = 2;
 * @return {!Array<!proto.google.v1.Sample>}
 */
proto.google.v1.Profile.prototype.getSampleList = function() {
  return /** @type{!Array<!proto.google.v1.Sample>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Sample, 2));
};


/**
 * @param {!Array<!proto.google.v1.Sample>} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setSampleList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.v1.Sample=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Sample}
 */
proto.google.v1.Profile.prototype.addSample = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.v1.Sample, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearSampleList = function() {
  return this.setSampleList([]);
};


/**
 * repeated Mapping mapping = 3;
 * @return {!Array<!proto.google.v1.Mapping>}
 */
proto.google.v1.Profile.prototype.getMappingList = function() {
  return /** @type{!Array<!proto.google.v1.Mapping>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Mapping, 3));
};


/**
 * @param {!Array<!proto.google.v1.Mapping>} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setMappingList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.v1.Mapping=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Mapping}
 */
proto.google.v1.Profile.prototype.addMapping = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.v1.Mapping, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearMappingList = function() {
  return this.setMappingList([]);
};


/**
 * repeated Location location = 4;
 * @return {!Array<!proto.google.v1.Location>}
 */
proto.google.v1.Profile.prototype.getLocationList = function() {
  return /** @type{!Array<!proto.google.v1.Location>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Location, 4));
};


/**
 * @param {!Array<!proto.google.v1.Location>} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setLocationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.v1.Location=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Location}
 */
proto.google.v1.Profile.prototype.addLocation = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.v1.Location, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearLocationList = function() {
  return this.setLocationList([]);
};


/**
 * repeated Function function = 5;
 * @return {!Array<!proto.google.v1.Function>}
 */
proto.google.v1.Profile.prototype.getFunctionList = function() {
  return /** @type{!Array<!proto.google.v1.Function>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Function, 5));
};


/**
 * @param {!Array<!proto.google.v1.Function>} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setFunctionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.v1.Function=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Function}
 */
proto.google.v1.Profile.prototype.addFunction = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.v1.Function, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearFunctionList = function() {
  return this.setFunctionList([]);
};


/**
 * repeated string string_table = 6;
 * @return {!Array<string>}
 */
proto.google.v1.Profile.prototype.getStringTableList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setStringTableList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.addStringTable = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearStringTableList = function() {
  return this.setStringTableList([]);
};


/**
 * optional int64 drop_frames = 7;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getDropFrames = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setDropFrames = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int64 keep_frames = 8;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getKeepFrames = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setKeepFrames = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 time_nanos = 9;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getTimeNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setTimeNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int64 duration_nanos = 10;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getDurationNanos = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setDurationNanos = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional ValueType period_type = 11;
 * @return {?proto.google.v1.ValueType}
 */
proto.google.v1.Profile.prototype.getPeriodType = function() {
  return /** @type{?proto.google.v1.ValueType} */ (
    jspb.Message.getWrapperField(this, proto.google.v1.ValueType, 11));
};


/**
 * @param {?proto.google.v1.ValueType|undefined} value
 * @return {!proto.google.v1.Profile} returns this
*/
proto.google.v1.Profile.prototype.setPeriodType = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearPeriodType = function() {
  return this.setPeriodType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.v1.Profile.prototype.hasPeriodType = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional int64 period = 12;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getPeriod = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setPeriod = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * repeated int64 comment = 13;
 * @return {!Array<number>}
 */
proto.google.v1.Profile.prototype.getCommentList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 13));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setCommentList = function(value) {
  return jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.addComment = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.clearCommentList = function() {
  return this.setCommentList([]);
};


/**
 * optional int64 default_sample_type = 14;
 * @return {number}
 */
proto.google.v1.Profile.prototype.getDefaultSampleType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Profile} returns this
 */
proto.google.v1.Profile.prototype.setDefaultSampleType = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.ValueType.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.ValueType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.ValueType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.ValueType.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    unit: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.ValueType}
 */
proto.google.v1.ValueType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.ValueType;
  return proto.google.v1.ValueType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.ValueType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.ValueType}
 */
proto.google.v1.ValueType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUnit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.ValueType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.ValueType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.ValueType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.ValueType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getUnit();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 type = 1;
 * @return {number}
 */
proto.google.v1.ValueType.prototype.getType = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.ValueType} returns this
 */
proto.google.v1.ValueType.prototype.setType = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 unit = 2;
 * @return {number}
 */
proto.google.v1.ValueType.prototype.getUnit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.ValueType} returns this
 */
proto.google.v1.ValueType.prototype.setUnit = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.v1.Sample.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Sample.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Sample.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Sample} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Sample.toObject = function(includeInstance, msg) {
  var f, obj = {
    locationIdList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    valueList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    labelList: jspb.Message.toObjectList(msg.getLabelList(),
    proto.google.v1.Label.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Sample}
 */
proto.google.v1.Sample.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Sample;
  return proto.google.v1.Sample.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Sample} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Sample}
 */
proto.google.v1.Sample.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedUint64() : [reader.readUint64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLocationId(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt64() : [reader.readInt64()]);
      for (var i = 0; i < values.length; i++) {
        msg.addValue(values[i]);
      }
      break;
    case 3:
      var value = new proto.google.v1.Label;
      reader.readMessage(value,proto.google.v1.Label.deserializeBinaryFromReader);
      msg.addLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Sample.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Sample.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Sample} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Sample.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocationIdList();
  if (f.length > 0) {
    writer.writePackedUint64(
      1,
      f
    );
  }
  f = message.getValueList();
  if (f.length > 0) {
    writer.writePackedInt64(
      2,
      f
    );
  }
  f = message.getLabelList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.v1.Label.serializeBinaryToWriter
    );
  }
};


/**
 * repeated uint64 location_id = 1;
 * @return {!Array<number>}
 */
proto.google.v1.Sample.prototype.getLocationIdList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.setLocationIdList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.addLocationId = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.clearLocationIdList = function() {
  return this.setLocationIdList([]);
};


/**
 * repeated int64 value = 2;
 * @return {!Array<number>}
 */
proto.google.v1.Sample.prototype.getValueList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.setValueList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.addValue = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.clearValueList = function() {
  return this.setValueList([]);
};


/**
 * repeated Label label = 3;
 * @return {!Array<!proto.google.v1.Label>}
 */
proto.google.v1.Sample.prototype.getLabelList = function() {
  return /** @type{!Array<!proto.google.v1.Label>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Label, 3));
};


/**
 * @param {!Array<!proto.google.v1.Label>} value
 * @return {!proto.google.v1.Sample} returns this
*/
proto.google.v1.Sample.prototype.setLabelList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.v1.Label=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Label}
 */
proto.google.v1.Sample.prototype.addLabel = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.v1.Label, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Sample} returns this
 */
proto.google.v1.Sample.prototype.clearLabelList = function() {
  return this.setLabelList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Label.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Label.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Label} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Label.toObject = function(includeInstance, msg) {
  var f, obj = {
    key: jspb.Message.getFieldWithDefault(msg, 1, 0),
    str: jspb.Message.getFieldWithDefault(msg, 2, 0),
    num: jspb.Message.getFieldWithDefault(msg, 3, 0),
    numUnit: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Label}
 */
proto.google.v1.Label.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Label;
  return proto.google.v1.Label.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Label} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Label}
 */
proto.google.v1.Label.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setKey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStr(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNum(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNumUnit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Label.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Label.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Label} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Label.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKey();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getStr();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getNum();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getNumUnit();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional int64 key = 1;
 * @return {number}
 */
proto.google.v1.Label.prototype.getKey = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Label} returns this
 */
proto.google.v1.Label.prototype.setKey = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 str = 2;
 * @return {number}
 */
proto.google.v1.Label.prototype.getStr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Label} returns this
 */
proto.google.v1.Label.prototype.setStr = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 num = 3;
 * @return {number}
 */
proto.google.v1.Label.prototype.getNum = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Label} returns this
 */
proto.google.v1.Label.prototype.setNum = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 num_unit = 4;
 * @return {number}
 */
proto.google.v1.Label.prototype.getNumUnit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Label} returns this
 */
proto.google.v1.Label.prototype.setNumUnit = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Mapping.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Mapping.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Mapping} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Mapping.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    memoryStart: jspb.Message.getFieldWithDefault(msg, 2, 0),
    memoryLimit: jspb.Message.getFieldWithDefault(msg, 3, 0),
    fileOffset: jspb.Message.getFieldWithDefault(msg, 4, 0),
    filename: jspb.Message.getFieldWithDefault(msg, 5, 0),
    buildId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    hasFunctions: jspb.Message.getBooleanFieldWithDefault(msg, 7, false),
    hasFilenames: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    hasLineNumbers: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
    hasInlineFrames: jspb.Message.getBooleanFieldWithDefault(msg, 10, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Mapping}
 */
proto.google.v1.Mapping.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Mapping;
  return proto.google.v1.Mapping.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Mapping} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Mapping}
 */
proto.google.v1.Mapping.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMemoryStart(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMemoryLimit(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFileOffset(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFilename(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setBuildId(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasFunctions(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasFilenames(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasLineNumbers(value);
      break;
    case 10:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasInlineFrames(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Mapping.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Mapping.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Mapping} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Mapping.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMemoryStart();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getMemoryLimit();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getFileOffset();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getFilename();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getBuildId();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getHasFunctions();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
  f = message.getHasFilenames();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getHasLineNumbers();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getHasInlineFrames();
  if (f) {
    writer.writeBool(
      10,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 memory_start = 2;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getMemoryStart = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setMemoryStart = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 memory_limit = 3;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getMemoryLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setMemoryLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 file_offset = 4;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getFileOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setFileOffset = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 filename = 5;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getFilename = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setFilename = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 build_id = 6;
 * @return {number}
 */
proto.google.v1.Mapping.prototype.getBuildId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setBuildId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional bool has_functions = 7;
 * @return {boolean}
 */
proto.google.v1.Mapping.prototype.getHasFunctions = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setHasFunctions = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


/**
 * optional bool has_filenames = 8;
 * @return {boolean}
 */
proto.google.v1.Mapping.prototype.getHasFilenames = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setHasFilenames = function(value) {
  return jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * optional bool has_line_numbers = 9;
 * @return {boolean}
 */
proto.google.v1.Mapping.prototype.getHasLineNumbers = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setHasLineNumbers = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional bool has_inline_frames = 10;
 * @return {boolean}
 */
proto.google.v1.Mapping.prototype.getHasInlineFrames = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 10, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.v1.Mapping} returns this
 */
proto.google.v1.Mapping.prototype.setHasInlineFrames = function(value) {
  return jspb.Message.setProto3BooleanField(this, 10, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.v1.Location.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Location.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Location.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Location} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Location.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    mappingId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    address: jspb.Message.getFieldWithDefault(msg, 3, 0),
    lineList: jspb.Message.toObjectList(msg.getLineList(),
    proto.google.v1.Line.toObject, includeInstance),
    isFolded: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Location}
 */
proto.google.v1.Location.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Location;
  return proto.google.v1.Location.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Location} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Location}
 */
proto.google.v1.Location.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setMappingId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setAddress(value);
      break;
    case 4:
      var value = new proto.google.v1.Line;
      reader.readMessage(value,proto.google.v1.Line.deserializeBinaryFromReader);
      msg.addLine(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsFolded(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Location.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Location.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Location} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Location.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getMappingId();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getAddress();
  if (f !== 0) {
    writer.writeUint64(
      3,
      f
    );
  }
  f = message.getLineList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.v1.Line.serializeBinaryToWriter
    );
  }
  f = message.getIsFolded();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.google.v1.Location.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Location} returns this
 */
proto.google.v1.Location.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint64 mapping_id = 2;
 * @return {number}
 */
proto.google.v1.Location.prototype.getMappingId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Location} returns this
 */
proto.google.v1.Location.prototype.setMappingId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint64 address = 3;
 * @return {number}
 */
proto.google.v1.Location.prototype.getAddress = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Location} returns this
 */
proto.google.v1.Location.prototype.setAddress = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Line line = 4;
 * @return {!Array<!proto.google.v1.Line>}
 */
proto.google.v1.Location.prototype.getLineList = function() {
  return /** @type{!Array<!proto.google.v1.Line>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.v1.Line, 4));
};


/**
 * @param {!Array<!proto.google.v1.Line>} value
 * @return {!proto.google.v1.Location} returns this
*/
proto.google.v1.Location.prototype.setLineList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.v1.Line=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.v1.Line}
 */
proto.google.v1.Location.prototype.addLine = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.v1.Line, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.v1.Location} returns this
 */
proto.google.v1.Location.prototype.clearLineList = function() {
  return this.setLineList([]);
};


/**
 * optional bool is_folded = 5;
 * @return {boolean}
 */
proto.google.v1.Location.prototype.getIsFolded = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.v1.Location} returns this
 */
proto.google.v1.Location.prototype.setIsFolded = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Line.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Line.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Line} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Line.toObject = function(includeInstance, msg) {
  var f, obj = {
    functionId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    line: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Line}
 */
proto.google.v1.Line.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Line;
  return proto.google.v1.Line.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Line} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Line}
 */
proto.google.v1.Line.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setFunctionId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLine(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Line.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Line.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Line} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Line.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFunctionId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getLine();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional uint64 function_id = 1;
 * @return {number}
 */
proto.google.v1.Line.prototype.getFunctionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Line} returns this
 */
proto.google.v1.Line.prototype.setFunctionId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 line = 2;
 * @return {number}
 */
proto.google.v1.Line.prototype.getLine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Line} returns this
 */
proto.google.v1.Line.prototype.setLine = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.v1.Function.prototype.toObject = function(opt_includeInstance) {
  return proto.google.v1.Function.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.v1.Function} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Function.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, 0),
    systemName: jspb.Message.getFieldWithDefault(msg, 3, 0),
    filename: jspb.Message.getFieldWithDefault(msg, 4, 0),
    startLine: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.v1.Function}
 */
proto.google.v1.Function.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.v1.Function;
  return proto.google.v1.Function.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.v1.Function} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.v1.Function}
 */
proto.google.v1.Function.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSystemName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setFilename(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStartLine(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.v1.Function.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.v1.Function.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.v1.Function} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.v1.Function.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint64(
      1,
      f
    );
  }
  f = message.getName();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getSystemName();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getFilename();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getStartLine();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
};


/**
 * optional uint64 id = 1;
 * @return {number}
 */
proto.google.v1.Function.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Function} returns this
 */
proto.google.v1.Function.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 name = 2;
 * @return {number}
 */
proto.google.v1.Function.prototype.getName = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Function} returns this
 */
proto.google.v1.Function.prototype.setName = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 system_name = 3;
 * @return {number}
 */
proto.google.v1.Function.prototype.getSystemName = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Function} returns this
 */
proto.google.v1.Function.prototype.setSystemName = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 filename = 4;
 * @return {number}
 */
proto.google.v1.Function.prototype.getFilename = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Function} returns this
 */
proto.google.v1.Function.prototype.setFilename = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int64 start_line = 5;
 * @return {number}
 */
proto.google.v1.Function.prototype.getStartLine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.v1.Function} returns this
 */
proto.google.v1.Function.prototype.setStartLine = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


goog.object.extend(exports, proto.google.v1);
