name: 'Manual Bun CI+CD'

on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: 'Release Version Tag (0.0.0)'
        required: true

jobs:
  bun:
    name: 'Build & Publish Bun'
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4.1.1'
        with:
          ref: ${{ github.ref }}
      - name: Check Docker secret presence
        id: checkdocker
        shell: bash
        run: |
          if [ "$SECRET" == "" ]; then
            echo "secretspresent=false" >> $GITHUB_OUTPUT
          else
            echo "secretspresent=true" >> $GITHUB_OUTPUT
          fi
        env:
          SECRET: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker QEMU
        if: ${{ steps.checkdocker.outputs.secretspresent }}
        uses: docker/setup-qemu-action@v3.0.0
        with:
           platforms: amd64, arm64
      - name: Set up Docker Buildx
        if: ${{ steps.checkdocker.outputs.secretspresent }}
        uses: docker/setup-buildx-action@v3.0.0
      - name: Login to DockerHub
        if: ${{ steps.checkdocker.outputs.secretspresent }}
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: Build and push to Docker Hub (bun)
        if: ${{ steps.checkdocker.outputs.secretspresent }}
        uses: docker/build-push-action@v5.0.0
        with:
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile_bun
          push: true
          tags: |
            qxip/qryn:bun
      - name: Log in to the GHCR registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GHCR (bun)
        uses: docker/build-push-action@v3.0.0
        with:
          platforms: linux/amd64, linux/arm64
          file: ./Dockerfile_bun
          push: true
          tags: |
             ghcr.io/metrico/qryn:bun
